site_name: histolytics docs
site_description: Documentation for Histolytics, a library for panoptic histopathology WSI analysis
site_author: Oskari Lehtonen
repo_url: https://github.com/HautaniemiLab/histolytics
repo_name: histolytics

theme:
  name: "material"
  logo: img/histolytics_thumbnail_logo.png
  favicon: img/favicon.ico
  palette:
    primary: black
    accent: cyan
  font:
    text: Raleway
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.copy
    - content.tabs.link
    - content.code.annotate
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes


plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            show_source: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - User Guide:
    - Model Fine-tuning: user_guide/fine_tuning.md
    - WSI Segmentation: user_guide/wsi_segmentation.md
    - Data Wrangling: user_guide/data_wrangling.md
  - Analysis Tutorials:
    - Nuclear Morphology: analysis_tutorials/nuclear_morphology.md
    - Chromatin Patterns: analysis_tutorials/chromatin_patterns.md
    - Collagen Fibers: analysis_tutorials/collagen_fibers.md
    - Stromal Morphology: analysis_tutorials/stromal_features.md
    - Spatial Neighborhoods: analysis_tutorials/neighborhood_analysis.md
    - Spatial Clustering: analysis_tutorials/clustering.md
  - API Reference:
    - WSI Segmenter: api/wsi_segmenter.md
    - Slide Reader: api/slide_reader.md
  - Contributing: contributing.md
