site_name: histolytics docs
site_description: Documentation for Histolytics, a library for panoptic histopathology WSI analysis
site_author: Oskari Lehtonen
site_url: https://HautaniemiLab.github.io/histolytics/
repo_url: https://github.com/HautaniemiLab/histolytics
repo_name: histolytics

theme:
  name: "material"
  logo: img/histolytics_thumbnail_logo.png
  favicon: img/favicon.ico
  palette:
    primary: black
    accent: cyan
  font:
    text: Raleway
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.copy
    - content.tabs.link
    - content.code.annotate
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - navigation.indexes

plugins:
  - search
  - social
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            show_source: true
  - mkdocs-jupyter:
      include: ["*.ipynb"]

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.arithmatex:
      generic: true
  - codehilite
  - markdown.extensions.def_list
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.keys
  - pymdownx.details
  - admonition
  - attr_list
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition

  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  - toc:
        permalink: true

extra_javascript:
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css



nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - User Guide:
    - Model Fine-tuning: user_guide/fine_tuning.md
    - WSI Segmentation: user_guide/wsi_segmentation.md
    - Data Wrangling: user_guide/data_wrangling.md
  - Analysis Tutorials:
    - Nuclear Morphology: analysis_tutorials/nuclear_morphology.md
    - Chromatin Patterns: analysis_tutorials/chromatin_patterns.md
    - Collagen Fibers: analysis_tutorials/collagen_fibers.md
    - Stromal Morphology: analysis_tutorials/stromal_features.md
    - Spatial Neighborhoods: analysis_tutorials/neighborhood_analysis.md
    - Spatial Clustering: analysis_tutorials/clustering.md
  - API Reference:
    - WSI Segmenter: api/wsi_segmenter.md
    - Slide Reader: api/slide_reader.md
  - Contributing: contributing.md
